# ==============================================================================
# CLUSTER: Provider Configuration
# ==============================================================================

# Standard AWS provider. Region comes from a variable so you can deploy the
# same code to multiple regions.
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      ManagedBy   = "Terraform"
      Project     = var.project_name
      Environment = var.environment
    }
  }
}

# ------------------------------------------------------------------------------
# Kubernetes provider.
# ------------------------------------------------------------------------------
# After EKS is created, Terraform may need to talk to the Kubernetes API (for
# example, to manage access entries). We authenticate using a short-lived token
# generated by the AWS provider's EKS auth data source. This avoids storing any
# kubeconfig on disk.
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This calls `aws eks get-token` under the hood to fetch a fresh token.
    args = ["eks", "get-token", "--cluster-name", module.eks.cluster_name, "--region", var.aws_region]
  }
}
